#!/usr/bin/env bash
# This script counts from 1 up to 100
# displays FizzBuzz if number is divisible by 15
# displays Buzz if number is divisible by 5
# displays Fizz if the number is divisible by 3
# else displays the number


for i in {1..100}
do
  if (( $i % 15 == 0 ))
  then
	echo "FizzBuzz"
  elif (( $i % 5 == 0 ))
  then
	echo "Buzz"
  elif (( $i % 3 == 0 ))
  then
	echo "Fizz"
  else
	echo "$i"
  	fi
done
