#!/usr/bin/env bash
# This script displays number from 1 to 20

# use case statement to display "bad luck from China" on 4th iteration
# use case statement to display "bad luck from Japan" on 9th iteration
# use case statement to display "bad luck from Italy" on 17th iteration


i=1

while [ $i -le 20 ]
do
	echo "$i "
  case $i in 
	  "4") echo "bad luck from China";;
	  "9") echo "bad luck from Japan";;
	  "17") echo "bad luck from Italy";;
  esac
  (( i++ ))
done
