#!/usr/bin/env bash
# This script displays word "Best School" ten times

h=0
m=1
while [ $h -le 12 ]
do
  echo "Hour: $h"
  while [ $m -lt 60 ]
  do 
	echo "$m"
  
  (( m++ ))
  done
m=1
(( h++ ))
done
