#!/usr/bin/env bash

# a program to read the content of the file 
 #if the file exists, print"file exists"
 #if the file doesn't exist, file does not exist
 #if the file is empty, file is empty...


if [ -e "school" ]
then
       echo "school file exists"
       if [ -s "school" ]
       then 
	echo "school file is not empty"
       else
        echo "school file is empty"
       fi
       
       if [ -f "school" ] 
       then
	 echo "school is a regular file"
       fi
else
  echo "school file does not exist"
fi
